set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(BUILD_SHARED_LIBS ON)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR})

if (NOT MSVC)
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")
endif()

set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)

option(ENABLE_DEBUG "Enable ENGINE_DEBUG macro" OFF)
if(ENABLE_DEBUG)
    add_compile_definitions(ENGINE_DEBUG=1)
    message(STATUS "INFO: ENGINE_DEBUG enabled")
endif()

option(ENABLE_TESTS "Enable building tests" OFF)

set_property(GLOBAL PROPERTY USE_FOLDERS ON)
